import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          {/* Include the JavaScript CDN */}
          <script src="https://hinkhoj.com/common/js/keyboard.js"></script>
          
          {/* Include the CSS CDN */}
         
        
          
          
        
        </head>
        <body className={inter.className}>
          {children}
          
          </body>
      </html>
  )
}
